'use strict';
const FURNITURE = {
'bed':['bed',29,34], 'bedside':['bedside table',14,21], 'desk':['desk',25,27], 'chair':['chair',13,27], 'wardrobe':['wardrobe',19,43], 'bookcase':['bookcase',19,41], 'sofa':['sofa',29,29], 'coffee-table':['coffee table',22,19], 'armchair':['armchair',21,29], 'side-table':['side table',14,22], 'tv-stand':['TV stand',27,23], 'office-chair':['office chair',16,30], 'cupboard':['cupboard',19,40], 'dining-table':['dining table',27,25], 'blue-chair':['blue chair',13,28], 'yellow-chair':['yellow chair',13,28], 'bench':['bench',25,24], 'sideboard':['sideboard',26,25], 'toy-chest':['toy chest',23,22], 'small-table':['small table',23,23], 'stool':['stool',12,21], 'drawers':['chest of drawers',20,29], 'gaming-chair':['gaming chair',16,31]
};
// Positions are neutral floor spaces, read from the viewer's perspective.
const SPOTS = [{x:20,y:75},{x:48,y:73},{x:73,y:77},{x:20,y:97},{x:48,y:97},{x:73,y:97}];
const ROOMS = [
{name:'Mia',title:'A cosy bedroom',bg:1,answer:['desk','bookcase','wardrobe','chair','bed','bedside'],text:"Hi! Can you help me with my bedroom? Put my desk under the window and a chair in front of it. My wardrobe goes beside the door, on its left. Put a bookcase between the desk and the wardrobe. I want my bed in the middle of the front row, away from the window. Finally, put the bedside table to the right of the bed. Now I have a lovely place to sleep and study!"},
{name:'Leo',title:'Movie night',bg:2,answer:['armchair','sofa','bookcase','side-table','coffee-table','tv-stand'],text:"Hello! Let's make my living room comfortable. Put an armchair under the window. My sofa goes to its right, between the armchair and the bookcase. The bookcase should be beside the door, on its left. Put the small side table in front of the armchair and the coffee table in front of the sofa. Finally, place the TV stand in front of the bookcase. I can't wait for our next film night!"},
{name:'Emma',title:'A little study',bg:3,answer:['sofa','bookcase','desk','coffee-table','cupboard','office-chair'],text:"Hi there! This is my new study. Please put the desk beside the door, on its left, with the office chair in front of it. I want the sofa under the window, not the desk. Put the bookcase between the sofa and the desk. The coffee table goes in front of the sofa. Finally, put the cupboard to the right of the coffee table, in the middle of the front row. Thank you for helping me!"},
{name:'Oliver',title:'Dinner together',bg:4,answer:['sideboard','bench','cupboard','blue-chair','dining-table','yellow-chair'],text:"Hello! Please help me get ready for dinner. Put the sideboard under the window. The cupboard goes beside the door, on its left. Put the bench between them. I want the dining table in front of the bench, in the middle of the front row. There are two chairs: the blue chair goes to the left of the table, and the yellow chair goes to its right. Please don't mix up the colours!"},
{name:'Sophie',title:'Time to play',bg:5,answer:['toy-chest','bookcase','cupboard','sofa','small-table','stool'],text:"Hi! I'd like a fun room for rainy days. Put the toy chest under the window and the cupboard beside the door, on its left. My bookcase goes between them. Place the small table in front of the bookcase. Put the sofa to the left of the table and the stool to its right. I don't want the stool near the window. Now I can play with my friends and put everything away afterwards!"},
{name:'Noah',title:'Be our guest',bg:6,answer:['armchair','drawers','wardrobe','side-table','bedside','bed'],text:"Hello! My cousin is coming to stay. Put the armchair under the window and the small side table in front of it. The wardrobe goes beside the door, on its left. Put the chest of drawers between the armchair and the wardrobe. I want the bed in front of the wardrobe. Finally, put the bedside table to the left of the bed, in the middle of the front row. I hope my cousin likes this room!"},
{name:'Alex',title:'Game on!',bg:7,answer:['desk','bookcase','cupboard','gaming-chair','sofa','coffee-table'],text:"Hey! Can you arrange my gaming room? Put the desk under the window and the gaming chair in front of it. My cupboard goes beside the door, on its left. Place the bookcase between the desk and the cupboard. I want the sofa in front of the bookcase. Don't put the coffee table in front of the sofa. Put it on the right side of the sofa instead. Now there's space for my friends!"},
{name:'Lily',title:'One more chapter',bg:8,answer:['armchair','bench','bookcase','side-table','sofa','coffee-table'],text:"Hello! I want a quiet place to read. Put the armchair under the window and the bookcase beside the door, on its left. The bench goes between the armchair and the bookcase. Put the small side table in front of the armchair. My sofa goes in front of the bench, in the middle of the front row. Finally, place the coffee table to the right of the sofa. Let's choose a book and relax!"}
];
